-- MySQL Script generated by MySQL Workbench
-- Sun Oct  5 10:21:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema E_Commerce_Online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema E_Commerce_Online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `E_Commerce_Online` DEFAULT CHARACTER SET utf8 ;
USE `E_Commerce_Online` ;

-- -----------------------------------------------------
-- Table `E_Commerce_Online`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce_Online`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipo` ENUM('PF', 'PJ') NOT NULL,
  `data_cadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E_Commerce_Online`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce_Online`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('Em processamento', 'Enviado', 'Entregue', 'Cancelado') NULL DEFAULT 'Em processamento',
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedido_cliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `E_Commerce_Online`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E_Commerce_Online`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce_Online`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NOT NULL,
  `forma_pagamento` ENUM('Cartão de crédito', 'cartão de débito', 'Boleto', 'Pix', 'Transferência Bancária') NOT NULL,
  `valor_pago` DECIMAL(10,2) NULL,
  `data_pagamento` DATETIME NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_pagamento_pedido_idx` (`idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `E_Commerce_Online`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E_Commerce_Online`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce_Online`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `contato` VARCHAR(20) NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E_Commerce_Online`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce_Online`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NULL,
  `idFornecedor` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_produto_fornecedor_idx` (`idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_produto_fornecedor`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `E_Commerce_Online`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E_Commerce_Online`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce_Online`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `idProduto` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`idEstoque`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_produto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `E_Commerce_Online`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E_Commerce_Online`.`Item_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce_Online`.`Item_Pedido` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `fk_produto_fornecedor_idx` (`idPedido` ASC) VISIBLE,
  INDEX `fk_itempedido_produto_idx` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_itempedido_pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `E_Commerce_Online`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itempedido_produto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `E_Commerce_Online`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E_Commerce_Online`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce_Online`.`Vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `ativo` ENUM('Sim', 'Não') NULL,
  PRIMARY KEY (`idVendedor`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
